/*
 * Kruise
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.openkruise.client.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ContainerRecreateRequestContainerRecreateState contains the recreation state of the container.
 */
@ApiModel(description = "ContainerRecreateRequestContainerRecreateState contains the recreation state of the container.")

public class KruiseAppsV1alpha1ContainerRecreateRequestContainerRecreateState {
  @SerializedName("message")
  private String message = null;

  @SerializedName("name")
  private String name = "";

  @SerializedName("phase")
  private String phase = "";

  public KruiseAppsV1alpha1ContainerRecreateRequestContainerRecreateState message(String message) {
    this.message = message;
    return this;
  }

   /**
   * A human readable message indicating details about this state.
   * @return message
  **/
  @ApiModelProperty(value = "A human readable message indicating details about this state.")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public KruiseAppsV1alpha1ContainerRecreateRequestContainerRecreateState name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of the container.
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Name of the container.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public KruiseAppsV1alpha1ContainerRecreateRequestContainerRecreateState phase(String phase) {
    this.phase = phase;
    return this;
  }

   /**
   * Phase indicates the recreation phase of the container.
   * @return phase
  **/
  @ApiModelProperty(required = true, value = "Phase indicates the recreation phase of the container.")
  public String getPhase() {
    return phase;
  }

  public void setPhase(String phase) {
    this.phase = phase;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KruiseAppsV1alpha1ContainerRecreateRequestContainerRecreateState kruiseAppsV1alpha1ContainerRecreateRequestContainerRecreateState = (KruiseAppsV1alpha1ContainerRecreateRequestContainerRecreateState) o;
    return Objects.equals(this.message, kruiseAppsV1alpha1ContainerRecreateRequestContainerRecreateState.message) &&
        Objects.equals(this.name, kruiseAppsV1alpha1ContainerRecreateRequestContainerRecreateState.name) &&
        Objects.equals(this.phase, kruiseAppsV1alpha1ContainerRecreateRequestContainerRecreateState.phase);
  }

  @Override
  public int hashCode() {
    return Objects.hash(message, name, phase);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KruiseAppsV1alpha1ContainerRecreateRequestContainerRecreateState {\n");
    
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    phase: ").append(toIndentedString(phase)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

