/*
 * Kruise
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.openkruise.client.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.openkruise.client.models.KruiseAppsPubRuntimeContainerMeta;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * RuntimeContainerMetaSet contains all the containers&#39; meta of the Pod.
 */
@ApiModel(description = "RuntimeContainerMetaSet contains all the containers' meta of the Pod.")

public class KruiseAppsPubRuntimeContainerMetaSet {
  @SerializedName("containers")
  private List<KruiseAppsPubRuntimeContainerMeta> containers = new ArrayList<KruiseAppsPubRuntimeContainerMeta>();

  public KruiseAppsPubRuntimeContainerMetaSet containers(List<KruiseAppsPubRuntimeContainerMeta> containers) {
    this.containers = containers;
    return this;
  }

  public KruiseAppsPubRuntimeContainerMetaSet addContainersItem(KruiseAppsPubRuntimeContainerMeta containersItem) {
    this.containers.add(containersItem);
    return this;
  }

   /**
   * Get containers
   * @return containers
  **/
  @ApiModelProperty(required = true, value = "")
  public List<KruiseAppsPubRuntimeContainerMeta> getContainers() {
    return containers;
  }

  public void setContainers(List<KruiseAppsPubRuntimeContainerMeta> containers) {
    this.containers = containers;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KruiseAppsPubRuntimeContainerMetaSet kruiseAppsPubRuntimeContainerMetaSet = (KruiseAppsPubRuntimeContainerMetaSet) o;
    return Objects.equals(this.containers, kruiseAppsPubRuntimeContainerMetaSet.containers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(containers);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KruiseAppsPubRuntimeContainerMetaSet {\n");
    
    sb.append("    containers: ").append(toIndentedString(containers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

