/*
 * Kruise
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.openkruise.client.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.openkruise.client.models.KruiseAppsV1alpha1ResourceDistributionNamespace;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * KruiseAppsV1alpha1ResourceDistributionTargetNamespaces
 */

public class KruiseAppsV1alpha1ResourceDistributionTargetNamespaces {
  @SerializedName("list")
  private List<KruiseAppsV1alpha1ResourceDistributionNamespace> list = null;

  public KruiseAppsV1alpha1ResourceDistributionTargetNamespaces list(List<KruiseAppsV1alpha1ResourceDistributionNamespace> list) {
    this.list = list;
    return this;
  }

  public KruiseAppsV1alpha1ResourceDistributionTargetNamespaces addListItem(KruiseAppsV1alpha1ResourceDistributionNamespace listItem) {
    if (this.list == null) {
      this.list = new ArrayList<KruiseAppsV1alpha1ResourceDistributionNamespace>();
    }
    this.list.add(listItem);
    return this;
  }

   /**
   * Get list
   * @return list
  **/
  @ApiModelProperty(value = "")
  public List<KruiseAppsV1alpha1ResourceDistributionNamespace> getList() {
    return list;
  }

  public void setList(List<KruiseAppsV1alpha1ResourceDistributionNamespace> list) {
    this.list = list;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KruiseAppsV1alpha1ResourceDistributionTargetNamespaces kruiseAppsV1alpha1ResourceDistributionTargetNamespaces = (KruiseAppsV1alpha1ResourceDistributionTargetNamespaces) o;
    return Objects.equals(this.list, kruiseAppsV1alpha1ResourceDistributionTargetNamespaces.list);
  }

  @Override
  public int hashCode() {
    return Objects.hash(list);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KruiseAppsV1alpha1ResourceDistributionTargetNamespaces {\n");
    
    sb.append("    list: ").append(toIndentedString(list)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

