/*
* Kruise
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.openkruise.client.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;
import javax.annotation.Generated;

/**
 * Template describes the subset that will be created.
 */
@ApiModel(description = "Template describes the subset that will be created.")
@Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-07-21T15:55:09.049+08:00")
public class KruiseAppsV1alpha1SubsetTemplate {
  @SerializedName("advancedStatefulSetTemplate")
  private KruiseAppsV1alpha1AdvancedStatefulSetTemplateSpec advancedStatefulSetTemplate = null;

  @SerializedName("cloneSetTemplate")
  private KruiseAppsV1alpha1CloneSetTemplateSpec cloneSetTemplate = null;

  @SerializedName("deploymentTemplate")
  private KruiseAppsV1alpha1DeploymentTemplateSpec deploymentTemplate = null;

  @SerializedName("statefulSetTemplate")
  private KruiseAppsV1alpha1StatefulSetTemplateSpec statefulSetTemplate = null;

  public KruiseAppsV1alpha1SubsetTemplate advancedStatefulSetTemplate(KruiseAppsV1alpha1AdvancedStatefulSetTemplateSpec advancedStatefulSetTemplate) {
    this.advancedStatefulSetTemplate = advancedStatefulSetTemplate;
    return this;
  }

   /**
   * Get advancedStatefulSetTemplate
   * @return advancedStatefulSetTemplate
  **/
  @ApiModelProperty(value = "")
  public KruiseAppsV1alpha1AdvancedStatefulSetTemplateSpec getAdvancedStatefulSetTemplate() {
    return advancedStatefulSetTemplate;
  }

  public void setAdvancedStatefulSetTemplate(KruiseAppsV1alpha1AdvancedStatefulSetTemplateSpec advancedStatefulSetTemplate) {
    this.advancedStatefulSetTemplate = advancedStatefulSetTemplate;
  }

  public KruiseAppsV1alpha1SubsetTemplate cloneSetTemplate(KruiseAppsV1alpha1CloneSetTemplateSpec cloneSetTemplate) {
    this.cloneSetTemplate = cloneSetTemplate;
    return this;
  }

   /**
   * Get cloneSetTemplate
   * @return cloneSetTemplate
  **/
  @ApiModelProperty(value = "")
  public KruiseAppsV1alpha1CloneSetTemplateSpec getCloneSetTemplate() {
    return cloneSetTemplate;
  }

  public void setCloneSetTemplate(KruiseAppsV1alpha1CloneSetTemplateSpec cloneSetTemplate) {
    this.cloneSetTemplate = cloneSetTemplate;
  }

  public KruiseAppsV1alpha1SubsetTemplate deploymentTemplate(KruiseAppsV1alpha1DeploymentTemplateSpec deploymentTemplate) {
    this.deploymentTemplate = deploymentTemplate;
    return this;
  }

   /**
   * Get deploymentTemplate
   * @return deploymentTemplate
  **/
  @ApiModelProperty(value = "")
  public KruiseAppsV1alpha1DeploymentTemplateSpec getDeploymentTemplate() {
    return deploymentTemplate;
  }

  public void setDeploymentTemplate(KruiseAppsV1alpha1DeploymentTemplateSpec deploymentTemplate) {
    this.deploymentTemplate = deploymentTemplate;
  }

  public KruiseAppsV1alpha1SubsetTemplate statefulSetTemplate(KruiseAppsV1alpha1StatefulSetTemplateSpec statefulSetTemplate) {
    this.statefulSetTemplate = statefulSetTemplate;
    return this;
  }

   /**
   * Get statefulSetTemplate
   * @return statefulSetTemplate
  **/
  @ApiModelProperty(value = "")
  public KruiseAppsV1alpha1StatefulSetTemplateSpec getStatefulSetTemplate() {
    return statefulSetTemplate;
  }

  public void setStatefulSetTemplate(KruiseAppsV1alpha1StatefulSetTemplateSpec statefulSetTemplate) {
    this.statefulSetTemplate = statefulSetTemplate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof KruiseAppsV1alpha1SubsetTemplate)) {
      return false;
    }
    KruiseAppsV1alpha1SubsetTemplate ioKruiseAppsV1alpha1UnitedDeploymentSpecTemplate = (KruiseAppsV1alpha1SubsetTemplate) o;
    return Objects.equals(this.advancedStatefulSetTemplate, ioKruiseAppsV1alpha1UnitedDeploymentSpecTemplate.advancedStatefulSetTemplate) &&
        Objects.equals(this.cloneSetTemplate, ioKruiseAppsV1alpha1UnitedDeploymentSpecTemplate.cloneSetTemplate) &&
        Objects.equals(this.deploymentTemplate, ioKruiseAppsV1alpha1UnitedDeploymentSpecTemplate.deploymentTemplate) &&
        Objects.equals(this.statefulSetTemplate, ioKruiseAppsV1alpha1UnitedDeploymentSpecTemplate.statefulSetTemplate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(advancedStatefulSetTemplate, cloneSetTemplate, deploymentTemplate, statefulSetTemplate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KruiseAppsV1alpha1UnitedDeploymentSpecTemplate {\n");
    
    sb.append("    advancedStatefulSetTemplate: ").append(toIndentedString(advancedStatefulSetTemplate)).append("\n");
    sb.append("    cloneSetTemplate: ").append(toIndentedString(cloneSetTemplate)).append("\n");
    sb.append("    deploymentTemplate: ").append(toIndentedString(deploymentTemplate)).append("\n");
    sb.append("    statefulSetTemplate: ").append(toIndentedString(statefulSetTemplate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

