/*
* Kruise
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.openkruise.client.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import javax.annotation.Generated;
import org.joda.time.DateTime;

/**
 * ResourceDistributionCondition allows a row to be marked with additional information.
 */
@ApiModel(description = "ResourceDistributionCondition allows a row to be marked with additional information.")
@Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-07-21T15:55:09.049+08:00")
public class KruiseAppsV1alpha1ResourceDistributionCondition {
  @SerializedName("failedNamespace")
  private List<String> failedNamespace = null;

  @SerializedName("lastTransitionTime")
  private DateTime lastTransitionTime = null;

  @SerializedName("reason")
  private String reason = null;

  @SerializedName("status")
  private String status = null;

  @SerializedName("type")
  private String type = null;

  public KruiseAppsV1alpha1ResourceDistributionCondition failedNamespace(List<String> failedNamespace) {
    this.failedNamespace = failedNamespace;
    return this;
  }

  public KruiseAppsV1alpha1ResourceDistributionCondition addFailedNamespaceItem(String failedNamespaceItem) {
    if (this.failedNamespace == null) {
      this.failedNamespace = new ArrayList<String>();
    }
    this.failedNamespace.add(failedNamespaceItem);
    return this;
  }

   /**
   * FailedNamespaces describe all failed namespaces when Status is False
   * @return failedNamespace
  **/
  @ApiModelProperty(value = "FailedNamespaces describe all failed namespaces when Status is False")
  public List<String> getFailedNamespace() {
    return failedNamespace;
  }

  public void setFailedNamespace(List<String> failedNamespace) {
    this.failedNamespace = failedNamespace;
  }

  public KruiseAppsV1alpha1ResourceDistributionCondition lastTransitionTime(DateTime lastTransitionTime) {
    this.lastTransitionTime = lastTransitionTime;
    return this;
  }

   /**
   * LastTransitionTime is the last time the condition transitioned from one status to another.
   * @return lastTransitionTime
  **/
  @ApiModelProperty(value = "LastTransitionTime is the last time the condition transitioned from one status to another.")
  public DateTime getLastTransitionTime() {
    return lastTransitionTime;
  }

  public void setLastTransitionTime(DateTime lastTransitionTime) {
    this.lastTransitionTime = lastTransitionTime;
  }

  public KruiseAppsV1alpha1ResourceDistributionCondition reason(String reason) {
    this.reason = reason;
    return this;
  }

   /**
   * Reason describe human readable message indicating details about last transition.
   * @return reason
  **/
  @ApiModelProperty(value = "Reason describe human readable message indicating details about last transition.")
  public String getReason() {
    return reason;
  }

  public void setReason(String reason) {
    this.reason = reason;
  }

  public KruiseAppsV1alpha1ResourceDistributionCondition status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Status of the condition, one of True, False, Unknown.
   * @return status
  **/
  @ApiModelProperty(required = true, value = "Status of the condition, one of True, False, Unknown.")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public KruiseAppsV1alpha1ResourceDistributionCondition type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Type of ResourceDistributionCondition.
   * @return type
  **/
  @ApiModelProperty(required = true, value = "Type of ResourceDistributionCondition.")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof KruiseAppsV1alpha1ResourceDistributionCondition)) {
      return false;
    }
    KruiseAppsV1alpha1ResourceDistributionCondition ioKruiseAppsV1alpha1ResourceDistributionStatusConditions = (KruiseAppsV1alpha1ResourceDistributionCondition) o;
    return Objects.equals(this.failedNamespace, ioKruiseAppsV1alpha1ResourceDistributionStatusConditions.failedNamespace) &&
        Objects.equals(this.lastTransitionTime, ioKruiseAppsV1alpha1ResourceDistributionStatusConditions.lastTransitionTime) &&
        Objects.equals(this.reason, ioKruiseAppsV1alpha1ResourceDistributionStatusConditions.reason) &&
        Objects.equals(this.status, ioKruiseAppsV1alpha1ResourceDistributionStatusConditions.status) &&
        Objects.equals(this.type, ioKruiseAppsV1alpha1ResourceDistributionStatusConditions.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(failedNamespace, lastTransitionTime, reason, status, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KruiseAppsV1alpha1ResourceDistributionStatusConditions {\n");
    
    sb.append("    failedNamespace: ").append(toIndentedString(failedNamespace)).append("\n");
    sb.append("    lastTransitionTime: ").append(toIndentedString(lastTransitionTime)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

