/*
* Kruise
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.openkruise.client.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;
import javax.annotation.Generated;

/**
 * Adaptive is used to communicate parameters when Type is AdaptiveWorkloadSpreadScheduleStrategyType.
 */
@ApiModel(description = "Adaptive is used to communicate parameters when Type is AdaptiveWorkloadSpreadScheduleStrategyType.")
@Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-07-21T15:55:09.049+08:00")
public class KruiseAppsV1alpha1AdaptiveWorkloadSpreadStrategy {
  @SerializedName("disableSimulationSchedule")
  private Boolean disableSimulationSchedule = null;

  @SerializedName("rescheduleCriticalSeconds")
  private Integer rescheduleCriticalSeconds = null;

  public KruiseAppsV1alpha1AdaptiveWorkloadSpreadStrategy disableSimulationSchedule(Boolean disableSimulationSchedule) {
    this.disableSimulationSchedule = disableSimulationSchedule;
    return this;
  }

   /**
   * DisableSimulationSchedule indicates whether to disable the feature of simulation schedule. Default is false. Webhook can take a simple general predicates to check whether Pod can be scheduled into this subset, but it just considers the Node resource and cannot replace scheduler to do richer predicates practically.
   * @return disableSimulationSchedule
  **/
  @ApiModelProperty(value = "DisableSimulationSchedule indicates whether to disable the feature of simulation schedule. Default is false. Webhook can take a simple general predicates to check whether Pod can be scheduled into this subset, but it just considers the Node resource and cannot replace scheduler to do richer predicates practically.")
  public Boolean isDisableSimulationSchedule() {
    return disableSimulationSchedule;
  }

  public void setDisableSimulationSchedule(Boolean disableSimulationSchedule) {
    this.disableSimulationSchedule = disableSimulationSchedule;
  }

  public KruiseAppsV1alpha1AdaptiveWorkloadSpreadStrategy rescheduleCriticalSeconds(Integer rescheduleCriticalSeconds) {
    this.rescheduleCriticalSeconds = rescheduleCriticalSeconds;
    return this;
  }

   /**
   * RescheduleCriticalSeconds indicates how long controller will reschedule a schedule failed Pod to the subset that has redundant capacity after the subset where the Pod lives. If a Pod was scheduled failed and still in a unschedulabe status over RescheduleCriticalSeconds duration, the controller will reschedule it to a suitable subset.
   * @return rescheduleCriticalSeconds
  **/
  @ApiModelProperty(value = "RescheduleCriticalSeconds indicates how long controller will reschedule a schedule failed Pod to the subset that has redundant capacity after the subset where the Pod lives. If a Pod was scheduled failed and still in a unschedulabe status over RescheduleCriticalSeconds duration, the controller will reschedule it to a suitable subset.")
  public Integer getRescheduleCriticalSeconds() {
    return rescheduleCriticalSeconds;
  }

  public void setRescheduleCriticalSeconds(Integer rescheduleCriticalSeconds) {
    this.rescheduleCriticalSeconds = rescheduleCriticalSeconds;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof KruiseAppsV1alpha1AdaptiveWorkloadSpreadStrategy)) {
      return false;
    }
    KruiseAppsV1alpha1AdaptiveWorkloadSpreadStrategy ioKruiseAppsV1alpha1WorkloadSpreadSpecScheduleStrategyAdaptive = (KruiseAppsV1alpha1AdaptiveWorkloadSpreadStrategy) o;
    return Objects.equals(this.disableSimulationSchedule, ioKruiseAppsV1alpha1WorkloadSpreadSpecScheduleStrategyAdaptive.disableSimulationSchedule) &&
        Objects.equals(this.rescheduleCriticalSeconds, ioKruiseAppsV1alpha1WorkloadSpreadSpecScheduleStrategyAdaptive.rescheduleCriticalSeconds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(disableSimulationSchedule, rescheduleCriticalSeconds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KruiseAppsV1alpha1WorkloadSpreadSpecScheduleStrategyAdaptive {\n");
    
    sb.append("    disableSimulationSchedule: ").append(toIndentedString(disableSimulationSchedule)).append("\n");
    sb.append("    rescheduleCriticalSeconds: ").append(toIndentedString(rescheduleCriticalSeconds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

