/*
 * Kruise
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.openkruise.client.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * KruiseAppsV1alpha1TransferEnvVar
 */

public class KruiseAppsV1alpha1TransferEnvVar {
  @SerializedName("envName")
  private String envName = null;

  @SerializedName("sourceContainerName")
  private String sourceContainerName = null;

  public KruiseAppsV1alpha1TransferEnvVar envName(String envName) {
    this.envName = envName;
    return this;
  }

   /**
   * Get envName
   * @return envName
  **/
  @ApiModelProperty(value = "")
  public String getEnvName() {
    return envName;
  }

  public void setEnvName(String envName) {
    this.envName = envName;
  }

  public KruiseAppsV1alpha1TransferEnvVar sourceContainerName(String sourceContainerName) {
    this.sourceContainerName = sourceContainerName;
    return this;
  }

   /**
   * Get sourceContainerName
   * @return sourceContainerName
  **/
  @ApiModelProperty(value = "")
  public String getSourceContainerName() {
    return sourceContainerName;
  }

  public void setSourceContainerName(String sourceContainerName) {
    this.sourceContainerName = sourceContainerName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KruiseAppsV1alpha1TransferEnvVar kruiseAppsV1alpha1TransferEnvVar = (KruiseAppsV1alpha1TransferEnvVar) o;
    return Objects.equals(this.envName, kruiseAppsV1alpha1TransferEnvVar.envName) &&
        Objects.equals(this.sourceContainerName, kruiseAppsV1alpha1TransferEnvVar.sourceContainerName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(envName, sourceContainerName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KruiseAppsV1alpha1TransferEnvVar {\n");
    
    sb.append("    envName: ").append(toIndentedString(envName)).append("\n");
    sb.append("    sourceContainerName: ").append(toIndentedString(sourceContainerName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

