/*
 * Kruise
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.openkruise.client.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.openkruise.client.models.KruiseAppsV1alpha1InPlaceUpdateContainerStatus;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.joda.time.DateTime;

import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * InPlaceUpdateState records latest inplace-update state, including old statuses of containers.
 */
@ApiModel(description = "InPlaceUpdateState records latest inplace-update state, including old statuses of containers.")

public class KruiseAppsV1alpha1InPlaceUpdateState {
  @SerializedName("lastContainerStatuses")
  private Map<String, KruiseAppsV1alpha1InPlaceUpdateContainerStatus> lastContainerStatuses = new HashMap<String, KruiseAppsV1alpha1InPlaceUpdateContainerStatus>();

  @SerializedName("revision")
  private String revision = null;

  @SerializedName("updateTimestamp")
  private DateTime updateTimestamp = null;

  public KruiseAppsV1alpha1InPlaceUpdateState lastContainerStatuses(Map<String, KruiseAppsV1alpha1InPlaceUpdateContainerStatus> lastContainerStatuses) {
    this.lastContainerStatuses = lastContainerStatuses;
    return this;
  }

  public KruiseAppsV1alpha1InPlaceUpdateState putLastContainerStatusesItem(String key, KruiseAppsV1alpha1InPlaceUpdateContainerStatus lastContainerStatusesItem) {
    this.lastContainerStatuses.put(key, lastContainerStatusesItem);
    return this;
  }

   /**
   * LastContainerStatuses records the before-in-place-update container statuses. It is a map from ContainerName to InPlaceUpdateContainerStatus
   * @return lastContainerStatuses
  **/
  @ApiModelProperty(required = true, value = "LastContainerStatuses records the before-in-place-update container statuses. It is a map from ContainerName to InPlaceUpdateContainerStatus")
  public Map<String, KruiseAppsV1alpha1InPlaceUpdateContainerStatus> getLastContainerStatuses() {
    return lastContainerStatuses;
  }

  public void setLastContainerStatuses(Map<String, KruiseAppsV1alpha1InPlaceUpdateContainerStatus> lastContainerStatuses) {
    this.lastContainerStatuses = lastContainerStatuses;
  }

  public KruiseAppsV1alpha1InPlaceUpdateState revision(String revision) {
    this.revision = revision;
    return this;
  }

   /**
   * Revision is the updated revision hash.
   * @return revision
  **/
  @ApiModelProperty(required = true, value = "Revision is the updated revision hash.")
  public String getRevision() {
    return revision;
  }

  public void setRevision(String revision) {
    this.revision = revision;
  }

  public KruiseAppsV1alpha1InPlaceUpdateState updateTimestamp(DateTime updateTimestamp) {
    this.updateTimestamp = updateTimestamp;
    return this;
  }

   /**
   * UpdateTimestamp is the time when the in-place update happens.
   * @return updateTimestamp
  **/
  @ApiModelProperty(required = true, value = "UpdateTimestamp is the time when the in-place update happens.")
  public DateTime getUpdateTimestamp() {
    return updateTimestamp;
  }

  public void setUpdateTimestamp(DateTime updateTimestamp) {
    this.updateTimestamp = updateTimestamp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KruiseAppsV1alpha1InPlaceUpdateState kruiseAppsV1alpha1InPlaceUpdateState = (KruiseAppsV1alpha1InPlaceUpdateState) o;
    return Objects.equals(this.lastContainerStatuses, kruiseAppsV1alpha1InPlaceUpdateState.lastContainerStatuses) &&
        Objects.equals(this.revision, kruiseAppsV1alpha1InPlaceUpdateState.revision) &&
        Objects.equals(this.updateTimestamp, kruiseAppsV1alpha1InPlaceUpdateState.updateTimestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lastContainerStatuses, revision, updateTimestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KruiseAppsV1alpha1InPlaceUpdateState {\n");
    
    sb.append("    lastContainerStatuses: ").append(toIndentedString(lastContainerStatuses)).append("\n");
    sb.append("    revision: ").append(toIndentedString(revision)).append("\n");
    sb.append("    updateTimestamp: ").append(toIndentedString(updateTimestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

