/*
* Kruise
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.openkruise.client.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import javax.annotation.Generated;

/**
 * WorkloadSpreadSpec defines the desired state of WorkloadSpread.
 */
@ApiModel(description = "WorkloadSpreadSpec defines the desired state of WorkloadSpread.")
@Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-07-21T15:55:09.049+08:00")
public class KruiseAppsV1alpha1WorkloadSpreadSpec {
  @SerializedName("scheduleStrategy")
  private KruiseAppsV1alpha1WorkloadSpreadScheduleStrategy scheduleStrategy = null;

  @SerializedName("subsets")
  private List<KruiseAppsV1alpha1WorkloadSpreadSubset> subsets = new ArrayList<KruiseAppsV1alpha1WorkloadSpreadSubset>();

  @SerializedName("targetRef")
  private KruiseAppsV1alpha1TargetReference targetRef = null;

  public KruiseAppsV1alpha1WorkloadSpreadSpec scheduleStrategy(KruiseAppsV1alpha1WorkloadSpreadScheduleStrategy scheduleStrategy) {
    this.scheduleStrategy = scheduleStrategy;
    return this;
  }

   /**
   * Get scheduleStrategy
   * @return scheduleStrategy
  **/
  @ApiModelProperty(value = "")
  public KruiseAppsV1alpha1WorkloadSpreadScheduleStrategy getScheduleStrategy() {
    return scheduleStrategy;
  }

  public void setScheduleStrategy(KruiseAppsV1alpha1WorkloadSpreadScheduleStrategy scheduleStrategy) {
    this.scheduleStrategy = scheduleStrategy;
  }

  public KruiseAppsV1alpha1WorkloadSpreadSpec subsets(List<KruiseAppsV1alpha1WorkloadSpreadSubset> subsets) {
    this.subsets = subsets;
    return this;
  }

  public KruiseAppsV1alpha1WorkloadSpreadSpec addSubsetsItem(KruiseAppsV1alpha1WorkloadSpreadSubset subsetsItem) {
    this.subsets.add(subsetsItem);
    return this;
  }

   /**
   * Subsets describes the pods distribution details between each of subsets.
   * @return subsets
  **/
  @ApiModelProperty(required = true, value = "Subsets describes the pods distribution details between each of subsets.")
  public List<KruiseAppsV1alpha1WorkloadSpreadSubset> getSubsets() {
    return subsets;
  }

  public void setSubsets(List<KruiseAppsV1alpha1WorkloadSpreadSubset> subsets) {
    this.subsets = subsets;
  }

  public KruiseAppsV1alpha1WorkloadSpreadSpec targetRef(KruiseAppsV1alpha1TargetReference targetRef) {
    this.targetRef = targetRef;
    return this;
  }

   /**
   * Get targetRef
   * @return targetRef
  **/
  @ApiModelProperty(required = true, value = "")
  public KruiseAppsV1alpha1TargetReference getTargetRef() {
    return targetRef;
  }

  public void setTargetRef(KruiseAppsV1alpha1TargetReference targetRef) {
    this.targetRef = targetRef;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof KruiseAppsV1alpha1WorkloadSpreadSpec)) {
      return false;
    }
    KruiseAppsV1alpha1WorkloadSpreadSpec ioKruiseAppsV1alpha1WorkloadSpreadSpec = (KruiseAppsV1alpha1WorkloadSpreadSpec) o;
    return Objects.equals(this.scheduleStrategy, ioKruiseAppsV1alpha1WorkloadSpreadSpec.scheduleStrategy) &&
        Objects.equals(this.subsets, ioKruiseAppsV1alpha1WorkloadSpreadSpec.subsets) &&
        Objects.equals(this.targetRef, ioKruiseAppsV1alpha1WorkloadSpreadSpec.targetRef);
  }

  @Override
  public int hashCode() {
    return Objects.hash(scheduleStrategy, subsets, targetRef);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KruiseAppsV1alpha1WorkloadSpreadSpec {\n");
    
    sb.append("    scheduleStrategy: ").append(toIndentedString(scheduleStrategy)).append("\n");
    sb.append("    subsets: ").append(toIndentedString(subsets)).append("\n");
    sb.append("    targetRef: ").append(toIndentedString(targetRef)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

