/*
* Kruise
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.openkruise.client.models;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import javax.annotation.Generated;
import org.joda.time.DateTime;

/**
 * EphemeralJobStatus defines the observed state of EphemeralJob
 */
@ApiModel(description = "EphemeralJobStatus defines the observed state of EphemeralJob")
@Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-07-21T15:55:09.049+08:00")
public class KruiseAppsV1alpha1EphemeralJobStatus {
  @SerializedName("completionTime")
  private DateTime completionTime = null;

  @SerializedName("conditions")
  private List<KruiseAppsV1alpha1JobCondition> conditions = null;

  @SerializedName("failed")
  private Integer failed = null;

  @SerializedName("match")
  private Integer match = null;

  @SerializedName("phase")
  private String phase = null;

  @SerializedName("running")
  private Integer running = null;

  @SerializedName("startTime")
  private DateTime startTime = null;

  @SerializedName("succeeded")
  private Integer succeeded = null;

  @SerializedName("waiting")
  private Integer waiting = null;

  public KruiseAppsV1alpha1EphemeralJobStatus completionTime(DateTime completionTime) {
    this.completionTime = completionTime;
    return this;
  }

   /**
   * Represents time when the job was completed. It is not guaranteed to be set in happens-before order across separate operations. It is represented in RFC3339 form and is in UTC.
   * @return completionTime
  **/
  @ApiModelProperty(value = "Represents time when the job was completed. It is not guaranteed to be set in happens-before order across separate operations. It is represented in RFC3339 form and is in UTC.")
  public DateTime getCompletionTime() {
    return completionTime;
  }

  public void setCompletionTime(DateTime completionTime) {
    this.completionTime = completionTime;
  }

  public KruiseAppsV1alpha1EphemeralJobStatus conditions(List<KruiseAppsV1alpha1JobCondition> conditions) {
    this.conditions = conditions;
    return this;
  }

  public KruiseAppsV1alpha1EphemeralJobStatus addConditionsItem(KruiseAppsV1alpha1JobCondition conditionsItem) {
    if (this.conditions == null) {
      this.conditions = new ArrayList<KruiseAppsV1alpha1JobCondition>();
    }
    this.conditions.add(conditionsItem);
    return this;
  }

   /**
   * INSERT ADDITIONAL STATUS FIELD - define observed state of cluster Important: Run \&quot;make\&quot; to regenerate code after modifying this file
   * @return conditions
  **/
  @ApiModelProperty(value = "INSERT ADDITIONAL STATUS FIELD - define observed state of cluster Important: Run \"make\" to regenerate code after modifying this file")
  public List<KruiseAppsV1alpha1JobCondition> getConditions() {
    return conditions;
  }

  public void setConditions(List<KruiseAppsV1alpha1JobCondition> conditions) {
    this.conditions = conditions;
  }

  public KruiseAppsV1alpha1EphemeralJobStatus failed(Integer failed) {
    this.failed = failed;
    return this;
  }

   /**
   * The number of pods which reached phase Failed.
   * @return failed
  **/
  @ApiModelProperty(value = "The number of pods which reached phase Failed.")
  public Integer getFailed() {
    return failed;
  }

  public void setFailed(Integer failed) {
    this.failed = failed;
  }

  public KruiseAppsV1alpha1EphemeralJobStatus match(Integer match) {
    this.match = match;
    return this;
  }

   /**
   * The number of total matched pods.
   * @return match
  **/
  @ApiModelProperty(value = "The number of total matched pods.")
  public Integer getMatch() {
    return match;
  }

  public void setMatch(Integer match) {
    this.match = match;
  }

  public KruiseAppsV1alpha1EphemeralJobStatus phase(String phase) {
    this.phase = phase;
    return this;
  }

   /**
   * The phase of the job.
   * @return phase
  **/
  @ApiModelProperty(value = "The phase of the job.")
  public String getPhase() {
    return phase;
  }

  public void setPhase(String phase) {
    this.phase = phase;
  }

  public KruiseAppsV1alpha1EphemeralJobStatus running(Integer running) {
    this.running = running;
    return this;
  }

   /**
   * The number of actively running pods.
   * @return running
  **/
  @ApiModelProperty(value = "The number of actively running pods.")
  public Integer getRunning() {
    return running;
  }

  public void setRunning(Integer running) {
    this.running = running;
  }

  public KruiseAppsV1alpha1EphemeralJobStatus startTime(DateTime startTime) {
    this.startTime = startTime;
    return this;
  }

   /**
   * Represents time when the job was acknowledged by the job controller. It is not guaranteed to be set in happens-before order across separate operations. It is represented in RFC3339 form and is in UTC.
   * @return startTime
  **/
  @ApiModelProperty(value = "Represents time when the job was acknowledged by the job controller. It is not guaranteed to be set in happens-before order across separate operations. It is represented in RFC3339 form and is in UTC.")
  public DateTime getStartTime() {
    return startTime;
  }

  public void setStartTime(DateTime startTime) {
    this.startTime = startTime;
  }

  public KruiseAppsV1alpha1EphemeralJobStatus succeeded(Integer succeeded) {
    this.succeeded = succeeded;
    return this;
  }

   /**
   * The number of pods which reached phase Succeeded.
   * @return succeeded
  **/
  @ApiModelProperty(value = "The number of pods which reached phase Succeeded.")
  public Integer getSucceeded() {
    return succeeded;
  }

  public void setSucceeded(Integer succeeded) {
    this.succeeded = succeeded;
  }

  public KruiseAppsV1alpha1EphemeralJobStatus waiting(Integer waiting) {
    this.waiting = waiting;
    return this;
  }

   /**
   * The number of waiting pods.
   * @return waiting
  **/
  @ApiModelProperty(value = "The number of waiting pods.")
  public Integer getWaiting() {
    return waiting;
  }

  public void setWaiting(Integer waiting) {
    this.waiting = waiting;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof KruiseAppsV1alpha1EphemeralJobStatus)) {
      return false;
    }
    KruiseAppsV1alpha1EphemeralJobStatus ioKruiseAppsV1alpha1EphemeralJobStatus = (KruiseAppsV1alpha1EphemeralJobStatus) o;
    return Objects.equals(this.completionTime, ioKruiseAppsV1alpha1EphemeralJobStatus.completionTime) &&
        Objects.equals(this.conditions, ioKruiseAppsV1alpha1EphemeralJobStatus.conditions) &&
        Objects.equals(this.failed, ioKruiseAppsV1alpha1EphemeralJobStatus.failed) &&
        Objects.equals(this.match, ioKruiseAppsV1alpha1EphemeralJobStatus.match) &&
        Objects.equals(this.phase, ioKruiseAppsV1alpha1EphemeralJobStatus.phase) &&
        Objects.equals(this.running, ioKruiseAppsV1alpha1EphemeralJobStatus.running) &&
        Objects.equals(this.startTime, ioKruiseAppsV1alpha1EphemeralJobStatus.startTime) &&
        Objects.equals(this.succeeded, ioKruiseAppsV1alpha1EphemeralJobStatus.succeeded) &&
        Objects.equals(this.waiting, ioKruiseAppsV1alpha1EphemeralJobStatus.waiting);
  }

  @Override
  public int hashCode() {
    return Objects.hash(completionTime, conditions, failed, match, phase, running, startTime, succeeded, waiting);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KruiseAppsV1alpha1EphemeralJobStatus {\n");
    
    sb.append("    completionTime: ").append(toIndentedString(completionTime)).append("\n");
    sb.append("    conditions: ").append(toIndentedString(conditions)).append("\n");
    sb.append("    failed: ").append(toIndentedString(failed)).append("\n");
    sb.append("    match: ").append(toIndentedString(match)).append("\n");
    sb.append("    phase: ").append(toIndentedString(phase)).append("\n");
    sb.append("    running: ").append(toIndentedString(running)).append("\n");
    sb.append("    startTime: ").append(toIndentedString(startTime)).append("\n");
    sb.append("    succeeded: ").append(toIndentedString(succeeded)).append("\n");
    sb.append("    waiting: ").append(toIndentedString(waiting)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

