/*
* Kruise
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.openkruise.client.models;

import com.google.gson.annotations.SerializedName;
import io.kubernetes.client.custom.IntOrString;
import io.kubernetes.client.openapi.models.V1LabelSelector;
import io.kubernetes.client.openapi.models.V1PodTemplateSpec;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Objects;
import javax.annotation.Generated;

/**
 * DaemonSetSpec defines the desired state of DaemonSet
 */
@ApiModel(description = "DaemonSetSpec defines the desired state of DaemonSet")
@Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-07-21T15:55:09.049+08:00")
public class KruiseAppsV1alpha1DaemonSetSpec {
  @SerializedName("burstReplicas")
  private IntOrString burstReplicas = null;

  @SerializedName("lifecycle")
  private KruiseAppsPubLifecycle lifecycle = null;

  @SerializedName("minReadySeconds")
  private Integer minReadySeconds = null;

  @SerializedName("revisionHistoryLimit")
  private Integer revisionHistoryLimit = null;

  @SerializedName("selector")
  private V1LabelSelector selector = null;

  @SerializedName("template")
  private V1PodTemplateSpec template = null;

  @SerializedName("updateStrategy")
  private KruiseAppsV1alpha1DaemonSetUpdateStrategy updateStrategy = null;

  public KruiseAppsV1alpha1DaemonSetSpec burstReplicas(IntOrString burstReplicas) {
    this.burstReplicas = burstReplicas;
    return this;
  }

   /**
   * BurstReplicas is a rate limiter for booting pods on a lot of pods. The default value is 250
   * @return burstReplicas
  **/
  @ApiModelProperty(value = "BurstReplicas is a rate limiter for booting pods on a lot of pods. The default value is 250")
  public IntOrString getBurstReplicas() {
    return burstReplicas;
  }

  public void setBurstReplicas(IntOrString burstReplicas) {
    this.burstReplicas = burstReplicas;
  }

  public KruiseAppsV1alpha1DaemonSetSpec lifecycle(KruiseAppsPubLifecycle lifecycle) {
    this.lifecycle = lifecycle;
    return this;
  }

   /**
   * Get lifecycle
   * @return lifecycle
  **/
  @ApiModelProperty(value = "")
  public KruiseAppsPubLifecycle getLifecycle() {
    return lifecycle;
  }

  public void setLifecycle(KruiseAppsPubLifecycle lifecycle) {
    this.lifecycle = lifecycle;
  }

  public KruiseAppsV1alpha1DaemonSetSpec minReadySeconds(Integer minReadySeconds) {
    this.minReadySeconds = minReadySeconds;
    return this;
  }

   /**
   * The minimum number of seconds for which a newly created DaemonSet pod should be ready without any of its container crashing, for it to be considered available. Defaults to 0 (pod will be considered available as soon as it is ready).
   * @return minReadySeconds
  **/
  @ApiModelProperty(value = "The minimum number of seconds for which a newly created DaemonSet pod should be ready without any of its container crashing, for it to be considered available. Defaults to 0 (pod will be considered available as soon as it is ready).")
  public Integer getMinReadySeconds() {
    return minReadySeconds;
  }

  public void setMinReadySeconds(Integer minReadySeconds) {
    this.minReadySeconds = minReadySeconds;
  }

  public KruiseAppsV1alpha1DaemonSetSpec revisionHistoryLimit(Integer revisionHistoryLimit) {
    this.revisionHistoryLimit = revisionHistoryLimit;
    return this;
  }

   /**
   * The number of old history to retain to allow rollback. This is a pointer to distinguish between explicit zero and not specified. Defaults to 10.
   * @return revisionHistoryLimit
  **/
  @ApiModelProperty(value = "The number of old history to retain to allow rollback. This is a pointer to distinguish between explicit zero and not specified. Defaults to 10.")
  public Integer getRevisionHistoryLimit() {
    return revisionHistoryLimit;
  }

  public void setRevisionHistoryLimit(Integer revisionHistoryLimit) {
    this.revisionHistoryLimit = revisionHistoryLimit;
  }

  public KruiseAppsV1alpha1DaemonSetSpec selector(V1LabelSelector selector) {
    this.selector = selector;
    return this;
  }

   /**
   * Get selector
   * @return selector
  **/
  @ApiModelProperty(required = true, value = "")
  public V1LabelSelector getSelector() {
    return selector;
  }

  public void setSelector(V1LabelSelector selector) {
    this.selector = selector;
  }

  public KruiseAppsV1alpha1DaemonSetSpec template(V1PodTemplateSpec template) {
    this.template = template;
    return this;
  }

   /**
   * An object that describes the pod that will be created. The DaemonSet will create exactly one copy of this pod on every node that matches the template&#39;s node selector (or on every node if no node selector is specified). More info: https://kubernetes.io/docs/concepts/workloads/controllers/replicationcontroller#pod-template
   * @return template
  **/
  @ApiModelProperty(required = true, value = "An object that describes the pod that will be created. The DaemonSet will create exactly one copy of this pod on every node that matches the template's node selector (or on every node if no node selector is specified). More info: https://kubernetes.io/docs/concepts/workloads/controllers/replicationcontroller#pod-template")
  public V1PodTemplateSpec getTemplate() {
    return template;
  }

  public void setTemplate(V1PodTemplateSpec template) {
    this.template = template;
  }

  public KruiseAppsV1alpha1DaemonSetSpec updateStrategy(KruiseAppsV1alpha1DaemonSetUpdateStrategy updateStrategy) {
    this.updateStrategy = updateStrategy;
    return this;
  }

   /**
   * Get updateStrategy
   * @return updateStrategy
  **/
  @ApiModelProperty(value = "")
  public KruiseAppsV1alpha1DaemonSetUpdateStrategy getUpdateStrategy() {
    return updateStrategy;
  }

  public void setUpdateStrategy(KruiseAppsV1alpha1DaemonSetUpdateStrategy updateStrategy) {
    this.updateStrategy = updateStrategy;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (!(o instanceof KruiseAppsV1alpha1DaemonSetSpec)) {
      return false;
    }
    KruiseAppsV1alpha1DaemonSetSpec ioKruiseAppsV1alpha1DaemonSetSpec = (KruiseAppsV1alpha1DaemonSetSpec) o;
    return Objects.equals(this.burstReplicas, ioKruiseAppsV1alpha1DaemonSetSpec.burstReplicas) &&
        Objects.equals(this.lifecycle, ioKruiseAppsV1alpha1DaemonSetSpec.lifecycle) &&
        Objects.equals(this.minReadySeconds, ioKruiseAppsV1alpha1DaemonSetSpec.minReadySeconds) &&
        Objects.equals(this.revisionHistoryLimit, ioKruiseAppsV1alpha1DaemonSetSpec.revisionHistoryLimit) &&
        Objects.equals(this.selector, ioKruiseAppsV1alpha1DaemonSetSpec.selector) &&
        Objects.equals(this.template, ioKruiseAppsV1alpha1DaemonSetSpec.template) &&
        Objects.equals(this.updateStrategy, ioKruiseAppsV1alpha1DaemonSetSpec.updateStrategy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(burstReplicas, lifecycle, minReadySeconds, revisionHistoryLimit, selector, template, updateStrategy);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KruiseAppsV1alpha1DaemonSetSpec {\n");
    
    sb.append("    burstReplicas: ").append(toIndentedString(burstReplicas)).append("\n");
    sb.append("    lifecycle: ").append(toIndentedString(lifecycle)).append("\n");
    sb.append("    minReadySeconds: ").append(toIndentedString(minReadySeconds)).append("\n");
    sb.append("    revisionHistoryLimit: ").append(toIndentedString(revisionHistoryLimit)).append("\n");
    sb.append("    selector: ").append(toIndentedString(selector)).append("\n");
    sb.append("    template: ").append(toIndentedString(template)).append("\n");
    sb.append("    updateStrategy: ").append(toIndentedString(updateStrategy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

