/*
 * Kruise
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.openkruise.client.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PullPolicy defines the policy of the pulling task
 */
@ApiModel(description = "PullPolicy defines the policy of the pulling task")

public class KruiseAppsV1alpha1PullPolicy {
  @SerializedName("backoffLimit")
  private Integer backoffLimit = null;

  @SerializedName("timeoutSeconds")
  private Integer timeoutSeconds = null;

  public KruiseAppsV1alpha1PullPolicy backoffLimit(Integer backoffLimit) {
    this.backoffLimit = backoffLimit;
    return this;
  }

   /**
   * Specifies the number of retries before marking the pulling task failed. Defaults to 3
   * @return backoffLimit
  **/
  @ApiModelProperty(value = "Specifies the number of retries before marking the pulling task failed. Defaults to 3")
  public Integer getBackoffLimit() {
    return backoffLimit;
  }

  public void setBackoffLimit(Integer backoffLimit) {
    this.backoffLimit = backoffLimit;
  }

  public KruiseAppsV1alpha1PullPolicy timeoutSeconds(Integer timeoutSeconds) {
    this.timeoutSeconds = timeoutSeconds;
    return this;
  }

   /**
   * Specifies the timeout of the pulling task. Defaults to 600
   * @return timeoutSeconds
  **/
  @ApiModelProperty(value = "Specifies the timeout of the pulling task. Defaults to 600")
  public Integer getTimeoutSeconds() {
    return timeoutSeconds;
  }

  public void setTimeoutSeconds(Integer timeoutSeconds) {
    this.timeoutSeconds = timeoutSeconds;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KruiseAppsV1alpha1PullPolicy kruiseAppsV1alpha1PullPolicy = (KruiseAppsV1alpha1PullPolicy) o;
    return Objects.equals(this.backoffLimit, kruiseAppsV1alpha1PullPolicy.backoffLimit) &&
        Objects.equals(this.timeoutSeconds, kruiseAppsV1alpha1PullPolicy.timeoutSeconds);
  }

  @Override
  public int hashCode() {
    return Objects.hash(backoffLimit, timeoutSeconds);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KruiseAppsV1alpha1PullPolicy {\n");
    
    sb.append("    backoffLimit: ").append(toIndentedString(backoffLimit)).append("\n");
    sb.append("    timeoutSeconds: ").append(toIndentedString(timeoutSeconds)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

