/*
 * Kruise
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.openkruise.client.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * KruiseAppsV1alpha1SidecarContainerUpgradeStrategy
 */

public class KruiseAppsV1alpha1SidecarContainerUpgradeStrategy {
  @SerializedName("hotUpgradeEmptyImage")
  private String hotUpgradeEmptyImage = null;

  @SerializedName("upgradeType")
  private String upgradeType = null;

  public KruiseAppsV1alpha1SidecarContainerUpgradeStrategy hotUpgradeEmptyImage(String hotUpgradeEmptyImage) {
    this.hotUpgradeEmptyImage = hotUpgradeEmptyImage;
    return this;
  }

   /**
   * when HotUpgrade, HotUpgradeEmptyImage is used to complete the hot upgrading process HotUpgradeEmptyImage is consistent of sidecar container in Command, Args, Liveness probe, etc. but it does no actual work.
   * @return hotUpgradeEmptyImage
  **/
  @ApiModelProperty(value = "when HotUpgrade, HotUpgradeEmptyImage is used to complete the hot upgrading process HotUpgradeEmptyImage is consistent of sidecar container in Command, Args, Liveness probe, etc. but it does no actual work.")
  public String getHotUpgradeEmptyImage() {
    return hotUpgradeEmptyImage;
  }

  public void setHotUpgradeEmptyImage(String hotUpgradeEmptyImage) {
    this.hotUpgradeEmptyImage = hotUpgradeEmptyImage;
  }

  public KruiseAppsV1alpha1SidecarContainerUpgradeStrategy upgradeType(String upgradeType) {
    this.upgradeType = upgradeType;
    return this;
  }

   /**
   * when sidecar container is stateless, use ColdUpgrade otherwise HotUpgrade are more HotUpgrade. examples for istio envoy container is suitable for HotUpgrade default is ColdUpgrade
   * @return upgradeType
  **/
  @ApiModelProperty(value = "when sidecar container is stateless, use ColdUpgrade otherwise HotUpgrade are more HotUpgrade. examples for istio envoy container is suitable for HotUpgrade default is ColdUpgrade")
  public String getUpgradeType() {
    return upgradeType;
  }

  public void setUpgradeType(String upgradeType) {
    this.upgradeType = upgradeType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KruiseAppsV1alpha1SidecarContainerUpgradeStrategy kruiseAppsV1alpha1SidecarContainerUpgradeStrategy = (KruiseAppsV1alpha1SidecarContainerUpgradeStrategy) o;
    return Objects.equals(this.hotUpgradeEmptyImage, kruiseAppsV1alpha1SidecarContainerUpgradeStrategy.hotUpgradeEmptyImage) &&
        Objects.equals(this.upgradeType, kruiseAppsV1alpha1SidecarContainerUpgradeStrategy.upgradeType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hotUpgradeEmptyImage, upgradeType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KruiseAppsV1alpha1SidecarContainerUpgradeStrategy {\n");
    
    sb.append("    hotUpgradeEmptyImage: ").append(toIndentedString(hotUpgradeEmptyImage)).append("\n");
    sb.append("    upgradeType: ").append(toIndentedString(upgradeType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

