/*
 * Kruise
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.openkruise.client.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * ManualUpdate is a update strategy which allows users to control the update progress by providing the partition of each subset.
 */
@ApiModel(description = "ManualUpdate is a update strategy which allows users to control the update progress by providing the partition of each subset.")

public class KruiseAppsV1alpha1ManualUpdate {
  @SerializedName("partitions")
  private Map<String, Integer> partitions = null;

  public KruiseAppsV1alpha1ManualUpdate partitions(Map<String, Integer> partitions) {
    this.partitions = partitions;
    return this;
  }

  public KruiseAppsV1alpha1ManualUpdate putPartitionsItem(String key, Integer partitionsItem) {
    if (this.partitions == null) {
      this.partitions = new HashMap<String, Integer>();
    }
    this.partitions.put(key, partitionsItem);
    return this;
  }

   /**
   * Indicates number of subset partition.
   * @return partitions
  **/
  @ApiModelProperty(value = "Indicates number of subset partition.")
  public Map<String, Integer> getPartitions() {
    return partitions;
  }

  public void setPartitions(Map<String, Integer> partitions) {
    this.partitions = partitions;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KruiseAppsV1alpha1ManualUpdate kruiseAppsV1alpha1ManualUpdate = (KruiseAppsV1alpha1ManualUpdate) o;
    return Objects.equals(this.partitions, kruiseAppsV1alpha1ManualUpdate.partitions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(partitions);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KruiseAppsV1alpha1ManualUpdate {\n");
    
    sb.append("    partitions: ").append(toIndentedString(partitions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

