/*
 * Kruise
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.openkruise.client.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kubernetes.client.openapi.models.V1beta1JobTemplateSpec;
import io.openkruise.client.models.KruiseAppsV1alpha1BroadcastJobTemplateSpec;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * KruiseAppsV1alpha1CronJobTemplate
 */

public class KruiseAppsV1alpha1CronJobTemplate {
  @SerializedName("broadcastJobTemplate")
  private KruiseAppsV1alpha1BroadcastJobTemplateSpec broadcastJobTemplate = null;

  @SerializedName("jobTemplate")
  private V1beta1JobTemplateSpec jobTemplate = null;

  public KruiseAppsV1alpha1CronJobTemplate broadcastJobTemplate(KruiseAppsV1alpha1BroadcastJobTemplateSpec broadcastJobTemplate) {
    this.broadcastJobTemplate = broadcastJobTemplate;
    return this;
  }

   /**
   * Specifies the broadcastjob that will be created when executing a BroadcastCronJob.
   * @return broadcastJobTemplate
  **/
  @ApiModelProperty(value = "Specifies the broadcastjob that will be created when executing a BroadcastCronJob.")
  public KruiseAppsV1alpha1BroadcastJobTemplateSpec getBroadcastJobTemplate() {
    return broadcastJobTemplate;
  }

  public void setBroadcastJobTemplate(KruiseAppsV1alpha1BroadcastJobTemplateSpec broadcastJobTemplate) {
    this.broadcastJobTemplate = broadcastJobTemplate;
  }

  public KruiseAppsV1alpha1CronJobTemplate jobTemplate(V1beta1JobTemplateSpec jobTemplate) {
    this.jobTemplate = jobTemplate;
    return this;
  }

   /**
   * Specifies the job that will be created when executing a CronJob.
   * @return jobTemplate
  **/
  @ApiModelProperty(value = "Specifies the job that will be created when executing a CronJob.")
  public V1beta1JobTemplateSpec getJobTemplate() {
    return jobTemplate;
  }

  public void setJobTemplate(V1beta1JobTemplateSpec jobTemplate) {
    this.jobTemplate = jobTemplate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KruiseAppsV1alpha1CronJobTemplate kruiseAppsV1alpha1CronJobTemplate = (KruiseAppsV1alpha1CronJobTemplate) o;
    return Objects.equals(this.broadcastJobTemplate, kruiseAppsV1alpha1CronJobTemplate.broadcastJobTemplate) &&
        Objects.equals(this.jobTemplate, kruiseAppsV1alpha1CronJobTemplate.jobTemplate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(broadcastJobTemplate, jobTemplate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KruiseAppsV1alpha1CronJobTemplate {\n");
    
    sb.append("    broadcastJobTemplate: ").append(toIndentedString(broadcastJobTemplate)).append("\n");
    sb.append("    jobTemplate: ").append(toIndentedString(jobTemplate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

