/*
* Kruise
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.openkruise.client.models;
import io.kubernetes.client.openapi.models.V1Probe;
import io.swagger.annotations.ApiModel;
import javax.annotation.Generated;

/**
 * container probe spec
 */
@ApiModel(description = "container probe spec")
@Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-07-21T15:55:09.049+08:00")
public class KruiseAppsV1alpha1ContainerProbeSpec extends V1Probe {
}

