/*
 * Kruise
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.openkruise.client.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.openkruise.client.models.KruiseAppsV1alpha1ManualUpdate;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * UnitedDeploymentUpdateStrategy defines the update performance when template of UnitedDeployment is changed.
 */
@ApiModel(description = "UnitedDeploymentUpdateStrategy defines the update performance when template of UnitedDeployment is changed.")

public class KruiseAppsV1alpha1UnitedDeploymentUpdateStrategy {
  @SerializedName("manualUpdate")
  private KruiseAppsV1alpha1ManualUpdate manualUpdate = null;

  @SerializedName("type")
  private String type = null;

  public KruiseAppsV1alpha1UnitedDeploymentUpdateStrategy manualUpdate(KruiseAppsV1alpha1ManualUpdate manualUpdate) {
    this.manualUpdate = manualUpdate;
    return this;
  }

   /**
   * Includes all of the parameters a Manual update strategy needs.
   * @return manualUpdate
  **/
  @ApiModelProperty(value = "Includes all of the parameters a Manual update strategy needs.")
  public KruiseAppsV1alpha1ManualUpdate getManualUpdate() {
    return manualUpdate;
  }

  public void setManualUpdate(KruiseAppsV1alpha1ManualUpdate manualUpdate) {
    this.manualUpdate = manualUpdate;
  }

  public KruiseAppsV1alpha1UnitedDeploymentUpdateStrategy type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Type of UnitedDeployment update strategy. Default is Manual.
   * @return type
  **/
  @ApiModelProperty(value = "Type of UnitedDeployment update strategy. Default is Manual.")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KruiseAppsV1alpha1UnitedDeploymentUpdateStrategy kruiseAppsV1alpha1UnitedDeploymentUpdateStrategy = (KruiseAppsV1alpha1UnitedDeploymentUpdateStrategy) o;
    return Objects.equals(this.manualUpdate, kruiseAppsV1alpha1UnitedDeploymentUpdateStrategy.manualUpdate) &&
        Objects.equals(this.type, kruiseAppsV1alpha1UnitedDeploymentUpdateStrategy.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(manualUpdate, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KruiseAppsV1alpha1UnitedDeploymentUpdateStrategy {\n");
    
    sb.append("    manualUpdate: ").append(toIndentedString(manualUpdate)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

