/*
 * Kruise
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.openkruise.client.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kubernetes.client.proto.Runtime.RawExtension;
import io.openkruise.client.models.KruiseAppsV1alpha1ResourceDistributionTargets;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ResourceDistributionSpec defines the desired state of ResourceDistribution.
 */
@ApiModel(description = "ResourceDistributionSpec defines the desired state of ResourceDistribution.")

public class KruiseAppsV1alpha1ResourceDistributionSpec {
  @SerializedName("resource")
  private RawExtension resource = null;

  @SerializedName("targets")
  private KruiseAppsV1alpha1ResourceDistributionTargets targets = null;

  public KruiseAppsV1alpha1ResourceDistributionSpec resource(RawExtension resource) {
    this.resource = resource;
    return this;
  }

   /**
   * Resource must be the complete yaml that users want to distribute.
   * @return resource
  **/
  @ApiModelProperty(required = true, value = "Resource must be the complete yaml that users want to distribute.")
  public RawExtension getResource() {
    return resource;
  }

  public void setResource(RawExtension resource) {
    this.resource = resource;
  }

  public KruiseAppsV1alpha1ResourceDistributionSpec targets(KruiseAppsV1alpha1ResourceDistributionTargets targets) {
    this.targets = targets;
    return this;
  }

   /**
   * Targets defines the namespaces that users want to distribute to.
   * @return targets
  **/
  @ApiModelProperty(required = true, value = "Targets defines the namespaces that users want to distribute to.")
  public KruiseAppsV1alpha1ResourceDistributionTargets getTargets() {
    return targets;
  }

  public void setTargets(KruiseAppsV1alpha1ResourceDistributionTargets targets) {
    this.targets = targets;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KruiseAppsV1alpha1ResourceDistributionSpec kruiseAppsV1alpha1ResourceDistributionSpec = (KruiseAppsV1alpha1ResourceDistributionSpec) o;
    return Objects.equals(this.resource, kruiseAppsV1alpha1ResourceDistributionSpec.resource) &&
        Objects.equals(this.targets, kruiseAppsV1alpha1ResourceDistributionSpec.targets);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resource, targets);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KruiseAppsV1alpha1ResourceDistributionSpec {\n");
    
    sb.append("    resource: ").append(toIndentedString(resource)).append("\n");
    sb.append("    targets: ").append(toIndentedString(targets)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

