/*
 * Kruise
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0.1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.openkruise.client.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.openkruise.client.models.KruiseAppsPubRuntimeContainerHashes;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * RuntimeContainerMeta contains the meta data of a runtime container.
 */
@ApiModel(description = "RuntimeContainerMeta contains the meta data of a runtime container.")

public class KruiseAppsPubRuntimeContainerMeta {
  @SerializedName("containerID")
  private String containerID = "";

  @SerializedName("hashes")
  private KruiseAppsPubRuntimeContainerHashes hashes = null;

  @SerializedName("name")
  private String name = "";

  @SerializedName("restartCount")
  private Integer restartCount = 0;

  public KruiseAppsPubRuntimeContainerMeta containerID(String containerID) {
    this.containerID = containerID;
    return this;
  }

   /**
   * Get containerID
   * @return containerID
  **/
  @ApiModelProperty(required = true, value = "")
  public String getContainerID() {
    return containerID;
  }

  public void setContainerID(String containerID) {
    this.containerID = containerID;
  }

  public KruiseAppsPubRuntimeContainerMeta hashes(KruiseAppsPubRuntimeContainerHashes hashes) {
    this.hashes = hashes;
    return this;
  }

   /**
   * Get hashes
   * @return hashes
  **/
  @ApiModelProperty(required = true, value = "")
  public KruiseAppsPubRuntimeContainerHashes getHashes() {
    return hashes;
  }

  public void setHashes(KruiseAppsPubRuntimeContainerHashes hashes) {
    this.hashes = hashes;
  }

  public KruiseAppsPubRuntimeContainerMeta name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public KruiseAppsPubRuntimeContainerMeta restartCount(Integer restartCount) {
    this.restartCount = restartCount;
    return this;
  }

   /**
   * Get restartCount
   * @return restartCount
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getRestartCount() {
    return restartCount;
  }

  public void setRestartCount(Integer restartCount) {
    this.restartCount = restartCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KruiseAppsPubRuntimeContainerMeta kruiseAppsPubRuntimeContainerMeta = (KruiseAppsPubRuntimeContainerMeta) o;
    return Objects.equals(this.containerID, kruiseAppsPubRuntimeContainerMeta.containerID) &&
        Objects.equals(this.hashes, kruiseAppsPubRuntimeContainerMeta.hashes) &&
        Objects.equals(this.name, kruiseAppsPubRuntimeContainerMeta.name) &&
        Objects.equals(this.restartCount, kruiseAppsPubRuntimeContainerMeta.restartCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(containerID, hashes, name, restartCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KruiseAppsPubRuntimeContainerMeta {\n");
    
    sb.append("    containerID: ").append(toIndentedString(containerID)).append("\n");
    sb.append("    hashes: ").append(toIndentedString(hashes)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    restartCount: ").append(toIndentedString(restartCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

